name: Build & push container image
on:
  push:
    branches:
      - tx_latency_measurement_cicd

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get AWS ops credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEV_IAM_ROLE_ARN }}
          role-session-name: github-action-tx-latency-measurement
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_DEV_ECR_REPOSITORY }}
        #          IMAGE_TAG: ${{ github.sha }}
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          for dir in */; do
            if [ -f "$dir/Dockerfile" ]; then
              echo "Building image in $dir"
              docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$dir-${GITHUB_REF_NAME}.${git_hash} .
          #            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHA-$IMAGE_TAG
          fi
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
